### ISSUE TITLE
h

### ISSUE THREAD

**Issue by stbischof** [de-jena/main#1]

**Comment by jenA** [comment]
I'm curious as to why you'd like me to contact you.

**Comment by stbischof** [comment]
It was all about your Username. You seems to be inactive (can only see Public action) any we want to ask you about the availability of the username. The City Jena in Germany wants to Host there open source projects (if possible) under this namespaces.
This is why i tried to contact you. Maybe the further conversation we can do via mail.

**Comment by jenA** [comment]
This account is not inactive and I have no plans to give the name up.
